generatorName: scala-play
outputDir: samples/client/petstore/scala-play
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/scala-play-client
additionalProperties:
  hideGenerationTimestamp: "true"
